### ISSUE TITLE
在python3.8环境下无法运行

### ISSUE THREAD

**Issue by blackpatton17** [Neet-Nestor/Discord-Bilibili-Bot#2]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
clone下来后无法运行运行run.sh。环境为python 3.8, mac os x 10.13.6.
log:
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "/Users/####/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/Users/####/.pyenv/versions/3.8.0/lib/python3.8/logging/__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

### Steps to reproduce

1. clone the reop
2. install requirements
3. invoke run.sh or run.py

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by blackpatton17** [comment]
设置python为3.7能解决问题
