### ISSUE TITLE
0 knowledge about programming and scripts please help

### ISSUE THREAD

**Issue by On99TurtleHead** [Neet-Nestor/Discord-Bilibili-Bot#3]
Opened run.bat and cmd prompt pops up and displayed the following text:

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "C:\Users\1\Documents\Discord-Bilibili-Bot\run.py", line 438, in <module>
    main()
  File "C:\Users\1\Documents\Discord-Bilibili-Bot\run.py", line 347, in main
    finalize_logging()
  File "C:\Users\1\Documents\Discord-Bilibili-Bot\run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 589, in __init__
    self._style.validate()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
![Annotation 2021-12-19 022114](https://user-images.githubusercontent.com/42119653/146651847-1b9a09fc-7801-450a-917f-ceaf629e828e.png)

**Comment by Neet-Nestor** [comment]
Hi @On99TurtleHead , thanks for reporting this.

After investigating, this is an issue of the old version [MusicBot](https://github.com/Just-Some-Bots/MusicBot) that this Bot was relying on and this problem only exists if you are using Python 3.8 instead of Python 3.7. 

I've ported a fix in commit 095cc8e3b10a644bb6e375aed7a315a58e45d1a6. If you pull the newest code, this error should be gone.

If this does not work, I will suggest you to use Python 3.7 instead.
